# Generated by Django 4.0.5 on 2022-07-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
